version: 2
updates:
  - package-ecosystem: npm
    open-pull-requests-limit: 10
    directory: '/'
    schedule:
      interval: weekly
      day: sunday
    versioning-strategy: widen
    labels:
      - dependencies
      - automerge

  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: 'monthly'
    labels:
      - dependencies
      - automerge
